---
- name: Проверка health-endpoint
  hosts: app
  tasks:
    - name: Проверка health-endpoint
      uri:
        url: "http://localhost/health"
        method: GET
        status_code: 200
        return_content: yes
      register: health_response
      retries: 5
      delay: 5
      until: health_response.status == 200

    - name: Вывод результата
      debug:
        msg: "Health check: {{ health_response.content }}"
