---
- name: Базовая настройка всех серверов
  hosts: all
  become: yes
  roles:
    - common

- name: Настройка приложения
  hosts: app
  become: yes
  roles:
    - app

- name: Настройка базы данных
  hosts: db
  become: yes
  roles:
    - db

- name: Настройка мониторинга
  hosts: monitoring
  become: yes
  roles:
    - monitoring
